### ISSUE TITLE
how to reverse painting for free style?

### ISSUE THREAD

**Issue by cnmade** [yellowQ-software/yellowQ-Flutter-Image-Painter#31]
How to painting and then reverse the painting area .
It just like put a full layer top the image, then using finger smearing the area user want to keep, after that, user will only to keep the area they want [the smeared area]

![image](https://user-images.githubusercontent.com/278153/171529888-f29e0883-5c00-4bca-84c9-02ca8494773a.png)

For the example, user really want to keep the area what the smeared by red color,

**Comment by lively-bigyan** [comment]
That is a pretty good idea but it kind of deviates a lot from the purpose of the package. I don't see that much of a use case for this kind of implementation especially because it kind of feels like the `Image Editor` kind of feature. You can easily implement the highlighting feature by adding your custom color like `Colors.red.withOpacity(0.3)` And use a filled box or painting with high strokeWidth.
