### ISSUE TITLE
Scaling mode is not preventing draw mode

### ISSUE THREAD

**Issue by Bonnyfication** [yellowQ-software/yellowQ-Flutter-Image-Painter#7]
### Problem
If the mode _scalable_ is set to true the ImagePainter does not prevent painting while scaling.
Also this mode should be called zoom instead of scaling because the scaling of the image is not saved.

### Solution
Implement a Listener wrapped around the canvas that handles the current FingerCount:

```
[...] Listener(
      onPointerDown: (_) => increaseFingerCount(),
      onPointerUp: (_) => decreaseFingerCount(),
      child: [...]
```

Then cancel painting when the fingerCount is == 2

```
if (_fingerCount == 2) {
   return;
}
```

**Comment by lively-bigyan** [comment]
Thank you for opening up the issue. The implementation was done on the previous versions of app but It felt kind of redundant to do this because painting begins when user starts touching. Although it did prevent further painting while zooming, it didn't do much for the initially painted ones so it was removed for latest versions during refactors. It will be included in future versions of the package. For the mode, I think your suggestion makes sense. I'll make sure to include that in upcoming versions.
