### ISSUE TITLE
Feature request: Set initial PaintMode

### ISSUE THREAD

**Issue by Bonnyfication** [yellowQ-software/yellowQ-Flutter-Image-Painter#8]
We would like to set the initial paint mode. Currently line is the default when opening the widget with an Image File. We would like to set the PaintMode to freeStyle.

Our current implementation and call of the ImagePainter looks like this:
```
ImagePainter.file(
          File(widget.imagePath),
          key: _imageKey,
          scalable: true,
        )
```

Is there a way to manipulate the controller in any way? Or should we fork this projekt to customize it further?

Thank you!

**Comment by lively-bigyan** [comment]
Controller was fully customizable on the previous versions of the package. But it is managed internally now because it involved too much coding on the users' part and it introduced unnecessary complications on the code. 100 lines of code is now reduced to 4,6 lines of code. Technically it should have a default controller and a customizable builder with all functionality being customizable by the users but right now because of the time constraints and lack of collaborations, I haven't been able to do that. What I can do is add initial paint mode. If you want to be able to do more than that, feel free to fork and customize and if you want to help the community, please create a PR so that all of the community can benefit from it. Thanks for the suggestions :)
