### ISSUE TITLE
PaintMode text does not work

### ISSUE THREAD

**Issue by Bonnyfication** [yellowQ-software/yellowQ-Flutter-Image-Painter#9]
### Problem

The dropdown of PaintMode includes _text_. If text is selected nothing happens. This mode is redundant because the text mode already exists in the action bar next to the stroke size selection.

Following this it would be nice to activate or deactivate features of the action bar and to restrict selection of the aviable paint modes.

**Comment by lively-bigyan** [comment]
Text works a little differently than other modes. Because in other modes, user interact directly with the screen but in the text mode user add text differently through a dialog. For the duration of text-mode selection, text can be moved around and places anywhere in the image. For that matter, text - mode selection requires additional work of adding text through an additional text button. But there is ongoing work on it to make it more natural and intuitive.
